development:
  adapter: mysql2
  database: angular_photo_storage
  username: root
  password: password
  host: localhost
test:
  adapter: mysql2
  database: angular_photo_storage_test
  username: root
  password: password
  host: localhost
production:
  adapter: mysql2
  database: angular_photo_storage
  username: root
  password: 
  host: localhost